const mongoose = require('mongoose');

const moderatorPriviligesSchema = new mongoose.Schema({
  privilegeId: { type: String, required: true },
  name: { type: String, required: true },
  description: { type: String, required: true }
}, { _id: false });

const bannedBySchema = new mongoose.Schema({
  id: { type: String, required: true },
  username: { type: String, required: true }
});

const statusSchema = new mongoose.Schema({
  emailVerified: { type: Boolean, default: false },
  autoGeneratedUsername: { type: Boolean, default: false },
  dateOfBirthApproximated: { type: Boolean, default: false },
  invalidEmail: { type: Boolean, default: false },
  missingRequiredInformation: { type: Boolean, default: false },
  pendingDeactivation: { type: Boolean, default: false },
  targetDeactivationDate: { type: Date, default: null },
  recoveringPassword: { type: Boolean, default: false },
  passwordUpdateRequired: { type: Boolean, default: false },
  passwordUpdateToken: { type: String, default: null },
  passwordResetSentDate: { type: Date, default: null },
  reserved: { type: Boolean, default: false },
  inactiveAccount: { type: Boolean, default: false },
  generalStatus: { type: String, default: "activated" },
  suspiciousActivity: { type: Boolean, default: false },
  locked: { type: Boolean, default: false },
  banned: { type: Boolean, default: false },
  bannedBy: { type: bannedBySchema, default: null },
  bannedReason: { type: String, default: null },
  minor: { type: Boolean, default: false },
  testAccount: { type: Boolean, default: false },
  phoneActivated: { type: Boolean, default: false },
  phoneSanctioned: { type: Boolean, default: false },
  invalidPhone: { type: Boolean, default: false },
  ageVerification: { type: String, default: "notVerified" },
  emailChangeInCooldown: { type: Date, default: null },
  acceptedTermsOfUse: { type: Boolean, default: false },
  emailVerificationSentDate: { type: Date, default: null },
  emailVerificationToken: { type: String, default: null },
  admin: { type: Boolean, default: false },
  moderator: { type: Boolean, default: false },
  moderatorPriviliges: { type: [moderatorPriviligesSchema], default: [] },
  // Quality Assurance
  qa: { type: Boolean, default: false },
  // JMCS Env
  jmcsEnv: { type: String, enum: ["prod", "dev"], default: "prod" },
  // 2FA
  twoFactorEnabled: { type: Boolean, default: false },
  twoFactorSecret: { type: String, default: null },
  // Password tracking
  passwordChangedAt: { type: Date, default: null },
  // Auth file password for game launcher
  authFilePassword: { type: String, default: null }
}, { _id: false });

const profileSchema = new mongoose.Schema({
  idOnPlatform: { type: String, default: "" },
  nameOnPlatform: { type: String },
  platformType: { type: String },
  profileId: { type: String },
  userId: { type: String },
  macAddress: { type: String }
}, { _id: false });

const hubSettingsSchema = mongoose.Schema({
  shareAccount: { type: Boolean, default: true },
  theme: { type: String, enum: ['dark', 'light'], default: 'light' },
  pushNotifications: { type: Boolean, default: false }
}, { _id: false })

const userSchema = new mongoose.Schema({
  userId: { type: String, unique: true, required: true },
  username: { type: String, unique: true, required: true },
  nameOnPlatform: { type: String, default: null },
  accountIssues: { type: String, default: null },
  communicationOptIn: { type: Boolean, default: false },
  communicationThirdPartyOptIn: { type: Boolean, default: false },
  country: { type: String, default: "US" },
  dateCreated: { type: Date, default: Date.now },
  dateAnonymized: { type: Date, default: null },
  dateOfBirth: { type: Date },
  email: { type: String, unique: true, required: true },
  firstName: { type: String, default: null },
  gender: { type: String, default: null },
  hasAcceptedLegalOptins: { type: Boolean, default: false },
  lastName: { type: String, default: null },
  preferredLanguage: { type: String, default: "en" },
  status: { type: statusSchema, default: () => ({}) },
  phone: { type: String, default: null },
  profiles: { type: [profileSchema], default: [] },
  accountType: { type: String, default: "Hub" },
  ageGroup: { type: String, default: "adult" },
  avatarId: { type: Number, default: 1 },
  // social fields
  friends: { type: [String], default: [] },
  friendRequestsReceived: { type: [String], default: [] },
  friendRequestsSent: { type: [String], default: [] },
  // security fields
  hashedPassword: { type: String, required: true },
  hubSettings: { type: hubSettingsSchema, default: () => ({}) },
  discord: {
    id: { type: String, default: null },
    username: { type: String, default: null },
    linkedAt: { type: Date, default: null }
  },
  patreon: {
    id: { type: String, default: null },
    memberId: { type: String, default: null },
    email: { type: String, default: null },
    fullName: { type: String, default: null },
    imageUrl: { type: String, default: null },
    vanity: { type: String, default: null },
    linkedAt: { type: Date, default: null },
    isSubscribed: { type: Boolean, default: false },
    lastCheckedAt: { type: Date, default: null }
  },
}, { timestamps: true });

const User = mongoose.model('User', userSchema);
module.exports = User;
